apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb-pod
        namespace: chat-app
    spec:
      containers:
      - name: chat-app-mongodb
        image: mongo:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INIT_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INIT_ROOT_UPASSWORD
          value: secret      
  
      volumes: 
       - name: mongo-data
         persistentVolumeClaim:
          claimName: mongodb-pvc

